### PR TITLE
Publish v6.2.0

### PR DESCRIPTION
**Pull request by daileytj**
#### Changes proposed in this Pull Request:

- Publishes v6.2.0

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
didn't notice earlier this morning in previous PR for 6.2.0 but all the sudden I'm getting this warning on shared prop

image

also didn't notice any updates for this either...

**Comment by daileytj** [comment]
I'll take a look at it @JeffGreiner-eaton

**Comment by daileytj** [comment]
> didn't notice this earlier this morning in previous PR for 6.2.0 but all the sudden I'm getting this warning on shared prop
> 
> image
> 
> also didn't notice any updates for this either...

Where are you seeing this?

**Comment by JeffGreiner-eaton** [comment]
> > didn't notice this earlier this morning in previous PR for 6.2.0 but all the sudden I'm getting this warning on shared prop
> > image
> > also didn't notice any updates for this either...
> 
> Where are you seeing this?

and drawer playground that contains the activeItemBackgroundColor

**Comment by huayunh** [comment]
I get this on my localhost too, but only with Drawer Rail Item.

**Comment by daileytj** [comment]
Fixed here https://github.com/etn-ccis/blui-react-component-library/pull/693

**Review by surajeaton — APPROVED** [review]
Looks good.

**Review by JeffGreiner-eaton — APPROVED** [review]

**Comment by JeffGreiner-eaton** [comment]
just update change log date and good to go

**Review by huayunh — APPROVED** [review]

**Pull request merged**
