### PR TITLE
BLUI-3902 re-usable playground component

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3902.

#### Changes proposed in this Pull Request:

-  Isolate playground component and refactor as a re-usable component

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- Uncomment the code in the `__configuration__/navigationMenu/navigation/tsx` in dev docs to add the test-playground routes. 
- Poke around and see how it all works.
- For now, all of the code for this component can be found in the `components/playground` folder, including the example screens and configs

### CODE REVIEW

**Comment by daileytj** [comment]
@joebochill What do we want to do with this?

**Comment by joebochill** [comment]
> @joebochill What do we want to do with this?

I don't understand the question. I assume we want to get reviews, approvals, and merge the code...am I missing something?

**Comment by daileytj** [comment]
> > @joebochill What do we want to do with this?
> 
> I don't understand the question. I assume we want to get reviews, approvals, and merge the code...am I missing something?

Right, I was wondering if this was going to be reviewed and merged, but no reviews in 2 weeks so I wasn't sure if this was going in now or just sitting in a branch for now

**Comment by joebochill** [comment]
> > > @joebochill What do we want to do with this?
> > 
> > 
> > I don't understand the question. I assume we want to get reviews, approvals, and merge the code...am I missing something?
> 
> Right, I was wondering if this was going to be reviewed and merged, but no reviews in 2 weeks so I wasn't sure if this was going in now or just sitting in a branch for now

Yes, we should get it in. It's isolated and doesn't affect the main app, so there's not harm in putting it into the working branch.

@JeffGreiner-eaton @surajeaton @huayunh

**Comment by huayunh** [comment]
I don't know. Are we still using the `release` branches?

**Comment by joebochill** [comment]
Let's merge it. I don't want to worry about losing it in a miscellaneous feature branch.`release/` branches are intended to be for _released_ code, not WIP.

**Pull request merged**
