### PR TITLE
Bug/fix undefined image

### PR DESCRIPTION
**Pull request by JeffGreiner-eaton**
Fixes https://github.com/etn-ccis/blui-react-component-library/issues/717.

#### Changes proposed in this Pull Request:

- Update getImage prop to be optional and set undefined
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
Feels like a hack when `url(undefined)` does not return 404. You did indeed get rid of the warning, but I'd prefer to see if you can get the `background-image` CSS rule to go away when `undefined` is selected by the user in the dropdown.

image

**Comment by JeffGreiner-eaton** [comment]
> Feels like a hack when `url(undefined)` does not return 404. You did indeed get rid of the warning, but I'd prefer to see if you can get the `background-image` CSS rule to go away when `undefined` is selected by the user in the dropdown.
> 
> image

For now I thinks its ok as is and since the utilities > getImage call will be refactored in the upcoming sprints.. @daileytj  what do you think

**Comment by daileytj** [comment]
> > Feels like a hack when `url(undefined)` does not return 404. You did indeed get rid of the warning, but I'd prefer to see if you can get the `background-image` CSS rule to go away when `undefined` is selected by the user in the dropdown.
> > image
> 
> For now I thinks its ok as is and since the utilities > getImage call will be refactored in the upcoming sprints.. @daileytj what do you think

I agree that this will be refactored, but it may be a while before we get to this so we should probably just fix it right now. Ideally, the getImage method call should not even get called unless there is an image.

**Review by huayunh — APPROVED** [review]

**Comment by huayunh** [comment]
Nice!

**Pull request merged**
